color: null
description: 'The text content for the About page.'
fieldLayouts:
  ab079ddb-75e9-43e7-84dc-56339678b2c8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-22T13:44:23+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 7af1dbde-ff2c-43d3-914f-6ab3e0881a00
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T13:47:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7a6fec95-2ed4-4d18-b669-9108357adc40 # Single Line Text
            handle: subheading
            includeInCards: false
            instructions: 'The subheading on the About Page'
            label: Subheading
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 77e3bd99-26cc-4c0a-957c-607645cc8ba4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-22T13:47:55+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: db17bc24-8930-4e0e-ab38-c2565b80dae6 # Rich Text
            handle: body
            includeInCards: false
            instructions: 'The content of the About page.'
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 806b3f00-3d2b-43f2-942a-d5d2fdb4b878
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: e50f3204-2631-40d2-9b22-4c0525d834ec
        userCondition: null
handle: about
hasTitleField: true
icon: address-card
name: About
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
