color: null
description: null
fieldLayouts:
  fc8506af-71d1-44b6-9110-8680d299a9ba:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-23T18:21:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: cd9c11b3-1c0d-4a4b-ae79-0936f8f95647 # Color
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 1933dd2a-2f26-48ef-9e6c-e50876e932d3
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-23T18:08:10+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 6e8faed9-e787-40bf-ad22-f989d41fbb1e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-23T18:21:12+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 23728677-e935-45a9-be09-8db255d1d4cb # Icon
            handle: titleIcon
            includeInCards: false
            instructions: null
            label: 'Title Icon'
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 3fb6dd2e-6aa2-46f7-977a-48040bd47fd9
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-23T18:56:21+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: db17bc24-8930-4e0e-ab38-c2565b80dae6 # Rich Text
            handle: body
            includeInCards: false
            instructions: null
            label: Body
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: bb5476af-672f-4691-95c0-7e811e12ee11
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-23T18:33:02+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 942ebfb2-eed8-462b-a9fe-651fba4a252f # List
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 311c8659-ba67-445a-8138-690adc40610e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-23T18:42:45+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 7a6fec95-2ed4-4d18-b669-9108357adc40 # Single Line Text
            handle: banner
            includeInCards: false
            instructions: null
            label: Banner
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 50374d72-3cc0-4346-b52d-b629e8c04435
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 85fa2848-d454-4b79-8330-34b0a8d40d68
        userCondition: null
handle: capability
hasTitleField: true
icon: check
name: Capability
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
