color: sky
description: 'List of organizations (schools or recruiters)'
fieldLayouts:
  2b2dbce9-04ea-4557-a730-a3cd98cb17e8:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-02T14:34:53+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: 'Enter the name of school or recruitment firm here.'
            label: 'Organization Name'
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 77259d36-9c83-4258-8d3e-e2ed481f5641
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-02T13:55:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 12d880c0-a281-4f27-a40b-135b2f5b4654 # Type of Organization
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd6bc44c-74a4-4179-ac11-1f4a1a9aa4bc
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-02T13:55:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 21bd4595-df6f-4876-9708-5bfadad51b42 # Website
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c77dc3b-1b9c-4a83-9c82-d59ab907585d
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-09-02T13:55:13+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: 9d8645b3-7788-49d7-92ef-e3c2e0aca352 # Logo
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 65f41962-ca3f-4635-99b8-173ff8449dcd
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 7b38dc28-cda6-4ff2-897c-c916436c4a1c
        userCondition: null
handle: organizations
hasTitleField: true
icon: school-flag
name: Organizations
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
