css: ".ck-editor__editable {\r\n    min-height: 250px;\r\n}"
headingLevels:
  - 1
  - 2
  - 3
  - 4
  - 5
  - 6
name: TBO
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - link
  - bulletedList
  - numberedList
  - sourceEditing
