altTranslationKeyFormat: null
altTranslationMethod: none
fieldLayouts:
  35239747-1838-4100-be3d-14e529f5d130:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-09-02T14:22:11+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            uid: af0feaac-92fd-4704-87e3-fc939f589659
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 350cccd3-8e8d-4018-ab29-bdeb6c375bc1
        userCondition: null
fs: assets
handle: logos
name: Logos
sortOrder: 1
subpath: logos
titleTranslationKeyFormat: null
titleTranslationMethod: site
transformFs: ''
transformSubpath: logos
