columnSuffix: null
handle: listItems
instructions: null
name: 'List Items'
searchable: false
settings:
  addRowLabel: 'Add a list item'
  columns:
    __assoc__:
      -
        - col1
        -
          __assoc__:
            -
              - heading
              - 'List Item'
            -
              - handle
              - listItem
            -
              - width
              - ''
            -
              - type
              - singleline
  defaults:
    -
      __assoc__:
        -
          - col1
          - ''
  maxRows: null
  minRows: null
  staticRows: false
translationKeyFormat: null
translationMethod: none
type: craft\fields\Table
