columnSuffix: null
handle: multiLineText
instructions: null
name: 'Multi Line Text'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  initialRows: 8
  multiline: true
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
