description: 'These users are school or recruiter representatives who will be allowed to post jobs on the site.'
handle: jobPosters
name: 'Job Posters'
permissions:
  - 'deleteassets:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'editimages:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'replacefiles:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'saveassets:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'viewassets:5de740b2-aa13-48eb-b460-549297b24e7d' # Logos
  - 'viewentries:7a30d7ad-a979-44b7-89f1-35059c005316' # Organizations
