defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 2956ebaa-8a8f-47ad-b082-2754cf28e9b0 # Homepage
handle: homepage
maxAuthors: 1
name: Homepage
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  62b64a73-e162-4b39-97d4-ac8246ccc3e5: # Blue Green Sheet
    enabledByDefault: true
    hasUrls: true
    template: index.twig
    uriFormat: __home__
type: single
